remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Graziano Blasilli
shortDescription: PhD Student in Visual Analytics and Cybersecurity at Sapienza Universit√† di Roma.
description:
logo: /assets/img/logo.png
show_downloads: false
google_analytics: G-PGDLTGVM20
